---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Welcome to GlycoDiveR

<!-- badges: start -->
<!-- badges: end -->

GlycoDiveR generates graphics from (quantitative) glycoproteomics 
    datasets directly from search engine output files. It currently supports 
    FragPipe, Byonic, pGlyco, Perseus, and MSstats output files. It converts the
    data into a generic GlycoDiveR format that incorporates key metadata along 
    with UniProt-derived metadata. The GlycoDiveR formatted input is directly 
    compatible with all GlycoDiveR graphics.

## Installation

You can install the development version of GlycoDiveR from [GitHub](https://github.com/) with:

``` r
devtools::install_github("riley-research/GlycoDiveR", build_vignettes = TRUE)

```

## How to get started

The Wiki tab on GitHub is a good starting point for learning how to use GlycoDiveR.
You can also use the links below to navigate to the different sections.

- [A basic example how to use GlycoDiveR](https://github.com/riley-research/GlycoDiveR)
- [How to import search engine outputs](https://github.com/riley-research/GlycoDiveR)
- [Manage databases to manage modifications, glycans, glycan colors, or the general color scheme](https://github.com/riley-research/GlycoDiveR)
- [GlycoDiveR's reference manual](https://github.com/riley-research/GlycoDiveR)

## Troubleshooting, tips, and ideas

For any troubleshooting, tips, and ideas please refer to the Issues tab on Github
or contact tveth@uw.edu.

<!-- You'll still need to render README.Rmd regularly to keep README.md up-to-date. devtools::build_readme() is handy for this. -->
