---
title: "Minimal Workflow Example"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 4
    toc_float: false
vignette: >
  %\VignetteIndexEntry{Minimal_Workflow_Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette shows the minimal R workflow to start plotting using FragPipe 
generated outputs.

```{r, eval = FALSE}
#1. Install GlycoDiveR. Make sure to regularly check for updates as new plots
#   and functionalities are frequently added.
if (!requireNamespace("GlycoDiveR", quietly = TRUE)) {
  devtools::install_github("riley-research/GlycoDiveR", build_vignettes = TRUE)
  
#2. Load the package
library(GlycoDiveR)
  
#3. Generate the annotation dataframe
GetAnnotationTemplate(path = "C:/pathToFolder", tool = "MSFragger")

#4. Make sure to fill in the csv file generated by the GetAnnotationTemplate function
#5. Run the importer function:
mydata <- ImportMSFragger(path = "C:/pathToFolder",
                       annotation = "C:/pathToFolder/annotation.csv",
                       fastaPath = "C:/pathToFolder/database-decoys-contam.fasta.fas",
                       normalization = "median",
                       peptideScoreCutoff = 0,
                       glycanScoreCutoff = 0.01)

#This is where you start plotting. For example:
PlotQuantificationQC(mydata)
```

